// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfbeudgccfosjlzgrrbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmYmV1ZGdjY2Zvc2psemdycmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjgwNzYsImV4cCI6MjA1NzY0NDA3Nn0.6Is-QG0an2N1NOxROnHk0-QpaaM3rNclePbIHyqX7Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);